// Mock data for AWS analytics
export const mockAwsData = {
  ec2Instances: 156,
  ec2InstancesUnpatched: 23,
  s3Buckets: 87,
  s3BucketsPublic: 5,
  iamUsers: 42,
  iamUsersWithoutMFA: 8,
  securityGroups: 65,
  securityGroupsWithIssues: 12,
  cloudTrailEvents: [
    { date: "2025-04-08", events: 12456 },
    { date: "2025-04-09", events: 13567 },
    { date: "2025-04-10", events: 11234 },
    { date: "2025-04-11", events: 14567 },
    { date: "2025-04-12", events: 15678 },
    { date: "2025-04-13", events: 16789 },
    { date: "2025-04-14", events: 17890 },
  ],
  vulnerabilitiesByService: [
    { service: "EC2", count: 45 },
    { service: "S3", count: 32 },
    { service: "IAM", count: 18 },
    { service: "RDS", count: 27 },
    { service: "Lambda", count: 15 },
    { service: "EKS", count: 23 },
  ],
  securityFindings: [
    {
      title: "Public S3 Bucket",
      resource: "company-data-backup",
      service: "S3",
      severity: "high",
      status: "active",
    },
    {
      title: "Unencrypted EBS Volume",
      resource: "i-0a1b2c3d4e5f6g7h8",
      service: "EC2",
      severity: "medium",
      status: "active",
    },
    {
      title: "Overly Permissive Security Group",
      resource: "sg-0a1b2c3d4e5f6g7h8",
      service: "EC2",
      severity: "high",
      status: "investigating",
    },
    {
      title: "IAM User with Admin Privileges",
      resource: "user/temp-admin",
      service: "IAM",
      severity: "critical",
      status: "active",
    },
    {
      title: "Unrotated Access Key",
      resource: "user/developer1",
      service: "IAM",
      severity: "medium",
      status: "resolved",
    },
    {
      title: "Unencrypted RDS Instance",
      resource: "db-prod-instance",
      service: "RDS",
      severity: "high",
      status: "investigating",
    },
    {
      title: "CloudTrail Logging Disabled",
      resource: "account",
      service: "CloudTrail",
      severity: "critical",
      status: "resolved",
    },
    {
      title: "Exposed Lambda Function URL",
      resource: "data-processor-function",
      service: "Lambda",
      severity: "medium",
      status: "active",
    },
  ],
}

// AWS CSPM Postures
export const awsCspmPostures = [
  {
    id: 1,
    name: "Root Account Usage",
    description: "Detect any use of the root account",
    status: "compliant", // compliant, warning, critical
    lastChecked: "2 hours ago",
    affectedResources: 0,
    category: "Identity",
    remediation: "Use IAM roles and users instead of the root account for all operations",
  },
  {
    id: 2,
    name: "MFA for All IAM Users",
    description: "Ensure MFA is enabled and enforced",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 5,
    category: "Identity",
    remediation: "Enable MFA for all IAM users with console access",
  },
  {
    id: 3,
    name: "Overly Permissive IAM Policies",
    description: "Detect wildcard * permissions or AdministratorAccess",
    status: "critical",
    lastChecked: "1 hour ago",
    affectedResources: 12,
    category: "Identity",
    remediation: "Review and restrict IAM policies to follow least privilege principle",
  },
  {
    id: 4,
    name: "Unrestricted Security Groups",
    description: "Check for open ports to the internet (0.0.0.0/0)",
    status: "critical",
    lastChecked: "30 minutes ago",
    affectedResources: 8,
    category: "Network",
    remediation: "Restrict security group rules to specific IP ranges and necessary ports",
  },
  {
    id: 5,
    name: "S3 Buckets Publicly Accessible",
    description: "Audit bucket policies and ACLs",
    status: "warning",
    lastChecked: "1 hour ago",
    affectedResources: 3,
    category: "Storage",
    remediation: "Remove public access permissions from S3 buckets",
  },
  {
    id: 6,
    name: "S3 Buckets Without Encryption at Rest",
    description: "Enforce SSE-S3 or SSE-KMS",
    status: "warning",
    lastChecked: "2 hours ago",
    affectedResources: 7,
    category: "Storage",
    remediation: "Enable default encryption for all S3 buckets",
  },
  {
    id: 7,
    name: "CloudTrail Not Enabled in All Regions",
    description: "Ensure full audit trail coverage",
    status: "compliant",
    lastChecked: "4 hours ago",
    affectedResources: 0,
    category: "Logging",
    remediation: "Enable CloudTrail in all regions with multi-region trail",
  },
  {
    id: 8,
    name: "CloudTrail Without Log File Validation",
    description: "Prevent tampering of logs",
    status: "compliant",
    lastChecked: "4 hours ago",
    affectedResources: 0,
    category: "Logging",
    remediation: "Enable log file validation for all CloudTrail trails",
  },
  {
    id: 9,
    name: "RDS Not Encrypted at Rest",
    description: "Check DB instances for encryption",
    status: "critical",
    lastChecked: "3 hours ago",
    affectedResources: 4,
    category: "Database",
    remediation: "Enable encryption for all RDS instances",
  },
  {
    id: 10,
    name: "IAM Access Keys Older Than 90 Days",
    description: "Rotate credentials regularly",
    status: "warning",
    lastChecked: "1 hour ago",
    affectedResources: 15,
    category: "Identity",
    remediation: "Implement a key rotation policy and automate rotation",
  },
  {
    id: 11,
    name: "EC2 Instances Without IMDSv2",
    description: "Block legacy metadata access (SSRF risk)",
    status: "warning",
    lastChecked: "2 hours ago",
    affectedResources: 23,
    category: "Compute",
    remediation: "Configure all instances to use IMDSv2 only",
  },
  {
    id: 12,
    name: "EBS Volumes Without Encryption",
    description: "Enforce at-rest encryption",
    status: "critical",
    lastChecked: "3 hours ago",
    affectedResources: 18,
    category: "Storage",
    remediation: "Enable EBS encryption by default and encrypt existing volumes",
  },
  {
    id: 13,
    name: "Lambda Functions Without VPC Isolation",
    description: "Avoid public execution contexts",
    status: "warning",
    lastChecked: "5 hours ago",
    affectedResources: 12,
    category: "Compute",
    remediation: "Configure Lambda functions to run within a VPC when accessing internal resources",
  },
  {
    id: 14,
    name: "GuardDuty Not Enabled in All Regions",
    description: "Ensure threat detection is active",
    status: "compliant",
    lastChecked: "6 hours ago",
    affectedResources: 0,
    category: "Security",
    remediation: "Enable GuardDuty in all regions",
  },
  {
    id: 15,
    name: "ELBs Without Access Logging",
    description: "Capture request-level data",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 5,
    category: "Network",
    remediation: "Enable access logs for all load balancers",
  },
  {
    id: 16,
    name: "CloudFront Without WAF Protection",
    description: "Filter web traffic properly",
    status: "critical",
    lastChecked: "3 hours ago",
    affectedResources: 2,
    category: "Network",
    remediation: "Associate AWS WAF with all CloudFront distributions",
  },
  {
    id: 17,
    name: "Unused Security Groups or Roles",
    description: "Remove stale permissions",
    status: "warning",
    lastChecked: "12 hours ago",
    affectedResources: 34,
    category: "Identity",
    remediation: "Identify and remove unused security groups and IAM roles",
  },
  {
    id: 18,
    name: "ECS Tasks Using Privileged Mode",
    description: "Avoid containers running as root",
    status: "warning",
    lastChecked: "8 hours ago",
    affectedResources: 7,
    category: "Compute",
    remediation: "Disable privileged mode for containers unless absolutely necessary",
  },
  {
    id: 19,
    name: "Sensitive Data in IAM Role Policies",
    description: "Detect secrets or keys in policy JSON",
    status: "compliant",
    lastChecked: "5 hours ago",
    affectedResources: 0,
    category: "Identity",
    remediation: "Use AWS Secrets Manager or Parameter Store for sensitive data",
  },
  {
    id: 20,
    name: "SNS Topics With Open Subscriptions",
    description: "Avoid accidental data exfiltration",
    status: "warning",
    lastChecked: "7 hours ago",
    affectedResources: 3,
    category: "Messaging",
    remediation: "Restrict SNS topic subscriptions to known endpoints",
  },
]

// AWS CSPM Summary Data
export const awsCspmSummary = {
  totalResources: 342,
  compliantResources: 267,
  warningResources: 52,
  criticalResources: 23,
  complianceScore: 78,
  lastScan: "2025-04-14 08:30 UTC",
  categoryCompliance: [
    { category: "Identity", compliant: 65, warning: 20, critical: 12 },
    { category: "Network", compliant: 42, warning: 8, critical: 10 },
    { category: "Storage", compliant: 53, warning: 10, critical: 0 },
    { category: "Compute", compliant: 78, warning: 12, critical: 0 },
    { category: "Database", compliant: 12, warning: 0, critical: 4 },
    { category: "Logging", compliant: 8, warning: 0, critical: 0 },
    { category: "Security", compliant: 5, warning: 2, critical: 0 },
    { category: "Messaging", compliant: 4, warning: 3, critical: 0 },
  ],
  trendData: [
    { date: "2025-04-08", compliant: 250, warning: 62, critical: 30 },
    { date: "2025-04-09", compliant: 255, warning: 60, critical: 27 },
    { date: "2025-04-10", compliant: 258, warning: 58, critical: 26 },
    { date: "2025-04-11", compliant: 260, warning: 57, critical: 25 },
    { date: "2025-04-12", compliant: 262, warning: 55, critical: 25 },
    { date: "2025-04-13", compliant: 265, warning: 54, critical: 23 },
    { date: "2025-04-14", compliant: 267, warning: 52, critical: 23 },
  ],
}
