// Mock data for Azure analytics
export const mockAzureData = {
  virtualMachines: 78,
  vmWithIssues: 15,
  storageAccounts: 34,
  publicStorageAccounts: 6,
  networkSecurityGroups: 45,
  nsgWithIssues: 9,
  keyVaults: 12,
  keyVaultsWithIssues: 3,
  securityScores: [
    { category: "Identity", score: 82 },
    { category: "Data", score: 75 },
    { category: "Devices", score: 68 },
    { category: "Apps", score: 79 },
    { category: "Infrastructure", score: 85 },
    { category: "Network", score: 72 },
  ],
  activityLogs: [
    { date: "2025-04-08", events: 8765 },
    { date: "2025-04-09", events: 9876 },
    { date: "2025-04-10", events: 7654 },
    { date: "2025-04-11", events: 8765 },
    { date: "2025-04-12", events: 9876 },
    { date: "2025-04-13", events: 10987 },
    { date: "2025-04-14", events: 12098 },
  ],
  securityRecommendations: [
    {
      recommendation: "Enable MFA for all users",
      resource: "Azure Active Directory",
      resourceType: "Identity",
      severity: "high",
      status: "open",
    },
    {
      recommendation: "Encrypt storage account",
      resource: "prod-storage",
      resourceType: "Storage",
      severity: "medium",
      status: "in_progress",
    },
    {
      recommendation: "Restrict network access to VM",
      resource: "app-server-01",
      resourceType: "Compute",
      severity: "high",
      status: "open",
    },
    {
      recommendation: "Enable diagnostic logging",
      resource: "web-app-service",
      resourceType: "App Service",
      severity: "medium",
      status: "open",
    },
    {
      recommendation: "Rotate storage account keys",
      resource: "logs-storage",
      resourceType: "Storage",
      severity: "medium",
      status: "resolved",
    },
    {
      recommendation: "Configure Azure Defender for SQL",
      resource: "prod-sql-server",
      resourceType: "Database",
      severity: "high",
      status: "in_progress",
    },
    {
      recommendation: "Implement Just-In-Time VM access",
      resource: "admin-jumpbox",
      resourceType: "Compute",
      severity: "high",
      status: "open",
    },
    {
      recommendation: "Enable Azure Policy",
      resource: "Subscription",
      resourceType: "Management",
      severity: "medium",
      status: "resolved",
    },
  ],
}

// Azure CSPM Postures
export const azureCspmPostures = [
  {
    id: 1,
    name: "Global Admin Accounts Without MFA",
    description: "Enforce MFA for privileged identities",
    status: "critical", // compliant, warning, critical
    lastChecked: "1 hour ago",
    affectedResources: 3,
    category: "Identity",
    remediation: "Enable and enforce MFA for all global administrator accounts",
  },
  {
    id: 2,
    name: "Legacy Authentication Enabled",
    description: "Disable protocols like POP/IMAP",
    status: "warning",
    lastChecked: "2 hours ago",
    affectedResources: 8,
    category: "Identity",
    remediation: "Disable legacy authentication protocols in Azure AD",
  },
  {
    id: 3,
    name: "External Users with Directory Roles",
    description: "Audit guest access privileges",
    status: "critical",
    lastChecked: "3 hours ago",
    affectedResources: 5,
    category: "Identity",
    remediation: "Review and remove directory roles from external/guest users",
  },
  {
    id: 4,
    name: "Storage Accounts Allowing Public Access",
    description: "Block anonymous access",
    status: "critical",
    lastChecked: "1 hour ago",
    affectedResources: 6,
    category: "Storage",
    remediation: "Disable public access on all storage accounts",
  },
  {
    id: 5,
    name: "Key Vaults Without Soft Delete Enabled",
    description: "Prevent permanent deletion",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 3,
    category: "Security",
    remediation: "Enable soft delete and purge protection for all key vaults",
  },
  {
    id: 6,
    name: "Unencrypted SQL Databases",
    description: "Enforce Transparent Data Encryption (TDE)",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 2,
    category: "Database",
    remediation: "Enable TDE for all SQL databases",
  },
  {
    id: 7,
    name: "NSGs Allowing Inbound from Internet (0.0.0.0/0)",
    description: "Check open ports",
    status: "critical",
    lastChecked: "1 hour ago",
    affectedResources: 9,
    category: "Network",
    remediation: "Review and restrict NSG rules to specific IP ranges",
  },
  {
    id: 8,
    name: "Inactive Users with Roles",
    description: "Detect dormant identities",
    status: "warning",
    lastChecked: "5 hours ago",
    affectedResources: 12,
    category: "Identity",
    remediation: "Remove roles from inactive user accounts",
  },
  {
    id: 9,
    name: "Log Analytics Not Linked to Resources",
    description: "Ensure monitoring coverage",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 15,
    category: "Monitoring",
    remediation: "Configure diagnostic settings to send logs to Log Analytics",
  },
  {
    id: 10,
    name: "Activity Log Not Retained for 365 Days",
    description: "Enforce long-term visibility",
    status: "compliant",
    lastChecked: "6 hours ago",
    affectedResources: 0,
    category: "Monitoring",
    remediation: "Configure log retention policy for at least 365 days",
  },
  {
    id: 11,
    name: "Resource Locks Missing for Critical Resources",
    description: "Prevent accidental deletion",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 18,
    category: "Management",
    remediation: "Apply delete locks to critical resources",
  },
  {
    id: 12,
    name: "Service Principals with Broad Permissions",
    description: "Audit app registrations",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 7,
    category: "Identity",
    remediation: "Review and restrict service principal permissions",
  },
  {
    id: 13,
    name: "Missing Diagnostic Settings on Resources",
    description: "Route logs to Log Analytics/Storage/EventHub",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 24,
    category: "Monitoring",
    remediation: "Configure diagnostic settings for all resources",
  },
  {
    id: 14,
    name: "App Services Using HTTP Instead of HTTPS",
    description: "Enforce secure transport",
    status: "critical",
    lastChecked: "1 hour ago",
    affectedResources: 4,
    category: "Web",
    remediation: "Configure HTTPS-only mode for all App Services",
  },
  {
    id: 15,
    name: "VMs Without Endpoint Protection",
    description: "Ensure Defender is installed and active",
    status: "warning",
    lastChecked: "2 hours ago",
    affectedResources: 11,
    category: "Compute",
    remediation: "Install and configure Microsoft Defender for Endpoint on all VMs",
  },
  {
    id: 16,
    name: "Access Reviews Not Configured",
    description: "Periodic access checks for users/groups",
    status: "warning",
    lastChecked: "7 hours ago",
    affectedResources: 1,
    category: "Identity",
    remediation: "Configure regular access reviews for privileged roles",
  },
  {
    id: 17,
    name: "RBAC Role Assignments at Subscription Scope",
    description: "Avoid excessive privileges",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 8,
    category: "Identity",
    remediation: "Limit role assignments to resource group or resource level",
  },
  {
    id: 18,
    name: "Expired Certificates in Use",
    description: "Detect TLS issues",
    status: "critical",
    lastChecked: "30 minutes ago",
    affectedResources: 2,
    category: "Security",
    remediation: "Renew or replace expired certificates",
  },
  {
    id: 19,
    name: "Missing Azure Policy Assignments",
    description: "Enforce compliance via policies",
    status: "compliant",
    lastChecked: "5 hours ago",
    affectedResources: 0,
    category: "Management",
    remediation: "Assign built-in or custom policies to enforce security standards",
  },
  {
    id: 20,
    name: "Unassociated Network Security Groups (NSGs)",
    description: "Remove or reassign",
    status: "compliant",
    lastChecked: "6 hours ago",
    affectedResources: 0,
    category: "Network",
    remediation: "Delete or associate unused NSGs",
  },
]

// Azure CSPM Summary Data
export const azureCspmSummary = {
  totalResources: 245,
  compliantResources: 156,
  warningResources: 58,
  criticalResources: 31,
  complianceScore: 64,
  lastScan: "2025-04-14 08:45 UTC",
  categoryCompliance: [
    { category: "Identity", compliant: 42, warning: 22, critical: 15 },
    { category: "Network", compliant: 28, warning: 8, critical: 9 },
    { category: "Storage", compliant: 25, warning: 3, critical: 6 },
    { category: "Compute", compliant: 32, warning: 11, critical: 0 },
    { category: "Database", compliant: 10, warning: 0, critical: 2 },
    { category: "Security", compliant: 8, warning: 3, critical: 2 },
    { category: "Monitoring", compliant: 5, warning: 9, critical: 0 },
    { category: "Management", compliant: 4, warning: 2, critical: 0 },
    { category: "Web", compliant: 2, warning: 0, critical: 4 },
  ],
  trendData: [
    { date: "2025-04-08", compliant: 142, warning: 65, critical: 38 },
    { date: "2025-04-09", compliant: 145, warning: 64, critical: 36 },
    { date: "2025-04-10", compliant: 148, warning: 62, critical: 35 },
    { date: "2025-04-11", compliant: 150, warning: 61, critical: 34 },
    { date: "2025-04-12", compliant: 152, warning: 60, critical: 33 },
    { date: "2025-04-13", compliant: 154, warning: 59, critical: 32 },
    { date: "2025-04-14", compliant: 156, warning: 58, critical: 31 },
  ],
}
