// Enhanced mock logs data structure that matches the API response format
export const enhancedMockLogs = {
  statusCode: 200,
  body: {
    message: "Successfully got logs!",
    affinity_logs: {
      records: [
        {
          type: "h2",
          timestamp: "2023-07-18T18:58:00Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "181.46.56.83",
          sourceport: "14003",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "-1",
          backendprocessingtime: "-1",
          responseprocessingtime: "-1",
          albstatuscode: "503",
          backendstatucode: "-",
          receivedbytes: "60",
          sentbytes: "635",
          requestverb: "GET",
          requesturl: "https://api.hermes.pollux.finance:443/socket.io/?room=hermes&EIO=4&transport=polling&t=ObgNeSN",
          requestproto: "HTTP/2.0",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e0e7-709ac58b1f7c00737adb062e",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "4",
          requestcreationtime: "2023-07-18T18:58:00Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "-",
          "target.portlist": "-",
          "target.codelist": "-",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
        {
          type: "h2",
          timestamp: "2023-07-18T18:57:45Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "192.168.1.25",
          sourceport: "12345",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "0.01",
          backendprocessingtime: "0.05",
          responseprocessingtime: "0.02",
          albstatuscode: "200",
          backendstatucode: "200",
          receivedbytes: "120",
          sentbytes: "1024",
          requestverb: "POST",
          requesturl: "https://api.hermes.pollux.finance:443/api/v1/transactions",
          requestproto: "HTTP/2.0",
          useragent:
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e0d9-1a2b3c4d5e6f7g8h9i0j1k2l",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "2",
          requestcreationtime: "2023-07-18T18:57:45Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "-",
          "target.portlist": "-",
          "target.codelist": "-",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
        {
          type: "h2",
          timestamp: "2023-07-18T18:57:30Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "203.0.113.42",
          sourceport: "54321",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "0.03",
          backendprocessingtime: "0.15",
          responseprocessingtime: "0.02",
          albstatuscode: "404",
          backendstatucode: "404",
          receivedbytes: "80",
          sentbytes: "512",
          requestverb: "GET",
          requesturl: "https://api.hermes.pollux.finance:443/api/v1/nonexistent",
          requestproto: "HTTP/2.0",
          useragent:
            "Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Mobile/15E148 Safari/604.1",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e0ca-a1b2c3d4e5f6g7h8i9j0k1l2",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "3",
          requestcreationtime: "2023-07-18T18:57:30Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "-",
          "target.portlist": "-",
          "target.codelist": "-",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
        {
          type: "h2",
          timestamp: "2023-07-18T18:57:15Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "198.51.100.73",
          sourceport: "33456",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "0.02",
          backendprocessingtime: "0.08",
          responseprocessingtime: "0.01",
          albstatuscode: "401",
          backendstatucode: "401",
          receivedbytes: "95",
          sentbytes: "320",
          requestverb: "PUT",
          requesturl: "https://api.hermes.pollux.finance:443/api/v1/users/profile",
          requestproto: "HTTP/2.0",
          useragent: "PostmanRuntime/7.32.3",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e0bb-m1n2o3p4q5r6s7t8u9v0w1x2",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "1",
          requestcreationtime: "2023-07-18T18:57:15Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "-",
          "target.portlist": "-",
          "target.codelist": "-",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
        {
          type: "h2",
          timestamp: "2023-07-18T18:57:00Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "10.0.0.15",
          sourceport: "22334",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "0.01",
          backendprocessingtime: "0.25",
          responseprocessingtime: "0.03",
          albstatuscode: "500",
          backendstatucode: "500",
          receivedbytes: "150",
          sentbytes: "480",
          requestverb: "DELETE",
          requesturl: "https://api.hermes.pollux.finance:443/api/v1/items/12345",
          requestproto: "HTTP/2.0",
          useragent:
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e0ac-y1z2a3b4c5d6e7f8g9h0i1j2",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "5",
          requestcreationtime: "2023-07-18T18:57:00Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "Internal Server Error",
          "target.portlist": "-",
          "target.codelist": "-",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
      ],
      execution_id: "3aefebf2-5e1b-4008-97cc-b84a053953da",
      headers: [
        "type",
        "timestamp",
        "albname",
        "sourceipaddress",
        "sourceport",
        "destinationipaddress",
        "destinationport",
        "requestprocessingtime",
        "backendprocessingtime",
        "responseprocessingtime",
        "albstatuscode",
        "backendstatucode",
        "receivedbytes",
        "sentbytes",
        "requestverb",
        "requesturl",
        "requestproto",
        "useragent",
        "sslcipher",
        "sslprotocol",
        "targetgrouparn",
        "traceid",
        "domainname",
        "chosencertarn",
        "matchedrulepriority",
        "requestcreationtime",
        "actionsexecuted",
        "redirecturl",
        "errorreason",
        "target.portlist",
        "target.codelist",
        "classification",
        "classificationreason",
        "customfield",
      ],
      records_per_page: 5,
      total_rows: 5,
    },
  },
}
