// Mock data for GCP analytics
export const mockGcpData = {
  computeInstances: 65,
  computeWithIssues: 12,
  storageBuckets: 43,
  publicBuckets: 7,
  firewallRules: 87,
  riskyFirewallRules: 15,
  iamRoles: 56,
  overPrivilegedRoles: 9,
  securityHealthByService: [
    { service: "Compute Engine", findings: 34 },
    { service: "Cloud Storage", findings: 27 },
    { service: "IAM", findings: 19 },
    { service: "Cloud SQL", findings: 23 },
    { service: "GKE", findings: 31 },
    { service: "Cloud Functions", findings: 15 },
  ],
  auditLogs: [
    { date: "2025-04-08", events: 7654 },
    { date: "2025-04-09", events: 8765 },
    { date: "2025-04-10", events: 6543 },
    { date: "2025-04-11", events: 7654 },
    { date: "2025-04-12", events: 8765 },
    { date: "2025-04-13", events: 9876 },
    { date: "2025-04-14", events: 10987 },
  ],
  securityFindings: [
    {
      finding: "Public Bucket Access",
      resource: "user-uploads-bucket",
      category: "Storage",
      severity: "high",
      status: "active",
    },
    {
      finding: "Unpatched VM Instance",
      resource: "web-server-01",
      category: "Compute",
      severity: "medium",
      status: "active",
    },
    {
      finding: "Overly Permissive Firewall",
      resource: "allow-all-ingress",
      category: "Network",
      severity: "critical",
      status: "in_progress",
    },
    {
      finding: "Service Account with Owner Role",
      resource: "app-service-account",
      category: "IAM",
      severity: "critical",
      status: "active",
    },
    {
      finding: "Unencrypted Disk",
      resource: "data-disk-01",
      category: "Compute",
      severity: "high",
      status: "resolved",
    },
    {
      finding: "SQL Instance Public IP",
      resource: "prod-postgres",
      category: "Database",
      severity: "high",
      status: "in_progress",
    },
    {
      finding: "API Key Exposed",
      resource: "maps-api-key",
      category: "API",
      severity: "medium",
      status: "resolved",
    },
    {
      finding: "Kubernetes Cluster Open Dashboard",
      resource: "prod-cluster",
      category: "GKE",
      severity: "high",
      status: "active",
    },
  ],
}

// GCP CSPM Postures
export const gcpCspmPostures = [
  {
    id: 1,
    name: "Cloud Storage Buckets Publicly Accessible",
    description: "Audit IAM and ACL policies",
    status: "critical", // compliant, warning, critical
    lastChecked: "1 hour ago",
    affectedResources: 7,
    category: "Storage",
    remediation: "Remove public access from storage buckets and enforce IAM policies",
  },
  {
    id: 2,
    name: "Compute Engine Instances Without Shielded VM Enabled",
    description: "Enforce hardened VMs",
    status: "warning",
    lastChecked: "2 hours ago",
    affectedResources: 15,
    category: "Compute",
    remediation: "Enable Shielded VM features for all Compute Engine instances",
  },
  {
    id: 3,
    name: "IAM Members With Basic Roles",
    description: "Replace with least privilege",
    status: "critical",
    lastChecked: "1 hour ago",
    affectedResources: 9,
    category: "Identity",
    remediation: "Replace Owner, Editor, Viewer roles with predefined or custom roles",
  },
  {
    id: 4,
    name: "Cloud Logging Not Enabled for All Services",
    description: "Ensure observability",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 12,
    category: "Monitoring",
    remediation: "Enable Cloud Logging for all services and resources",
  },
  {
    id: 5,
    name: "Service Accounts With Broad Access or Key Rotation Disabled",
    description: "Enforce strict roles",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 8,
    category: "Identity",
    remediation: "Review service account permissions and implement key rotation",
  },
  {
    id: 6,
    name: "BigQuery Datasets Without Encryption",
    description: "Use CMEK or default encryption",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 5,
    category: "Data",
    remediation: "Enable encryption for all BigQuery datasets",
  },
  {
    id: 7,
    name: "No VPC Flow Logs",
    description: "Monitor network activity",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 6,
    category: "Network",
    remediation: "Enable VPC flow logs for all subnets",
  },
  {
    id: 8,
    name: "Missing Organization Policy for Domain Restrictions",
    description: "Enforce allowed domains for identities",
    status: "compliant",
    lastChecked: "5 hours ago",
    affectedResources: 0,
    category: "Identity",
    remediation: "Configure organization policy to restrict identities to approved domains",
  },
  {
    id: 9,
    name: "No MFA for Admin Accounts",
    description: "Enforce 2-step verification",
    status: "critical",
    lastChecked: "1 hour ago",
    affectedResources: 4,
    category: "Identity",
    remediation: "Enable and enforce MFA for all admin accounts via Google Workspace",
  },
  {
    id: 10,
    name: "Public IPs on Compute Instances",
    description: "Avoid direct exposure",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 12,
    category: "Network",
    remediation: "Use Cloud NAT and remove public IPs from instances where possible",
  },
  {
    id: 11,
    name: "Cloud Functions Without Identity Binding",
    description: "Enforce least-privilege execution",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 8,
    category: "Serverless",
    remediation: "Configure service account identity for all Cloud Functions",
  },
  {
    id: 12,
    name: "Default Network Still Present",
    description: "Remove unused and open defaults",
    status: "warning",
    lastChecked: "6 hours ago",
    affectedResources: 1,
    category: "Network",
    remediation: "Delete default networks and create custom VPCs with proper security controls",
  },
  {
    id: 13,
    name: "No Audit Logs for Admin Activity",
    description: "Enforce log retention",
    status: "compliant",
    lastChecked: "5 hours ago",
    affectedResources: 0,
    category: "Monitoring",
    remediation: "Configure audit logging for admin activity and data access",
  },
  {
    id: 14,
    name: "No Billing Alert Thresholds",
    description: "Prevent cost overruns",
    status: "warning",
    lastChecked: "12 hours ago",
    affectedResources: 1,
    category: "Management",
    remediation: "Configure billing alerts and budget notifications",
  },
  {
    id: 15,
    name: "Firewall Rules Allowing 0.0.0.0/0",
    description: "Audit ingress settings",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 15,
    category: "Network",
    remediation: "Restrict firewall rules to specific IP ranges and necessary ports",
  },
  {
    id: 16,
    name: "GKE Clusters With Legacy Auth",
    description: "Remove basic auth/static credentials",
    status: "critical",
    lastChecked: "3 hours ago",
    affectedResources: 3,
    category: "Containers",
    remediation: "Disable basic authentication and use GCP IAM for cluster authentication",
  },
  {
    id: 17,
    name: "GKE Clusters Without Pod Security Policies",
    description: "Enforce RBAC and PSP",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 5,
    category: "Containers",
    remediation: "Enable Pod Security Policies for all GKE clusters",
  },
  {
    id: 18,
    name: "Secrets Stored in Plaintext",
    description: "Use Secret Manager",
    status: "critical",
    lastChecked: "1 hour ago",
    affectedResources: 18,
    category: "Security",
    remediation: "Move secrets from environment variables to Secret Manager",
  },
  {
    id: 19,
    name: "No Constraints on External IPs for VMs",
    description: "Avoid unintentional exposure",
    status: "warning",
    lastChecked: "5 hours ago",
    affectedResources: 7,
    category: "Compute",
    remediation: "Implement organization policy to restrict external IP addresses",
  },
  {
    id: 20,
    name: "Cloud DNS Zones With Public Exposure",
    description: "Restrict visibility",
    status: "compliant",
    lastChecked: "6 hours ago",
    affectedResources: 0,
    category: "Network",
    remediation: "Review and restrict DNS zone visibility",
  },
]

// GCP CSPM Summary Data
export const gcpCspmSummary = {
  totalResources: 198,
  compliantResources: 112,
  warningResources: 47,
  criticalResources: 39,
  complianceScore: 57,
  lastScan: "2025-04-14 09:00 UTC",
  categoryCompliance: [
    { category: "Identity", compliant: 25, warning: 8, critical: 13 },
    { category: "Network", compliant: 18, warning: 14, critical: 15 },
    { category: "Storage", compliant: 15, warning: 0, critical: 7 },
    { category: "Compute", compliant: 22, warning: 15, critical: 0 },
    { category: "Containers", compliant: 8, warning: 5, critical: 3 },
    { category: "Security", compliant: 5, warning: 0, critical: 18 },
    { category: "Monitoring", compliant: 12, warning: 5, critical: 0 },
    { category: "Management", compliant: 3, warning: 1, critical: 0 },
    { category: "Data", compliant: 3, warning: 5, critical: 0 },
    { category: "Serverless", compliant: 1, warning: 8, critical: 0 },
  ],
  trendData: [
    { date: "2025-04-08", compliant: 98, warning: 55, critical: 45 },
    { date: "2025-04-09", compliant: 102, warning: 53, critical: 43 },
    { date: "2025-04-10", compliant: 105, warning: 51, critical: 42 },
    { date: "2025-04-11", compliant: 107, warning: 50, critical: 41 },
    { date: "2025-04-12", compliant: 109, warning: 49, critical: 40 },
    { date: "2025-04-13", compliant: 110, warning: 48, critical: 40 },
    { date: "2025-04-14", compliant: 112, warning: 47, critical: 39 },
  ],
}
