// Mock data for GitHub analytics
export const mockGithubData = {
  repositories: 87,
  publicRepos: 12,
  vulnerabilities: 34,
  criticalVulnerabilities: 8,
  secretScans: 156,
  secretsFound: 23,
  codeScans: 78,
  codeIssues: 45,
  vulnerabilitiesOverTime: [
    { date: "2025-04-08", count: 42 },
    { date: "2025-04-09", count: 38 },
    { date: "2025-04-10", count: 35 },
    { date: "2025-04-11", count: 40 },
    { date: "2025-04-12", count: 36 },
    { date: "2025-04-13", count: 34 },
    { date: "2025-04-14", count: 34 },
  ],
  repositoryActivity: [
    { repository: "backend-api", commits: 156, pullRequests: 23 },
    { repository: "frontend-app", commits: 234, pullRequests: 45 },
    { repository: "data-processor", commits: 87, pullRequests: 12 },
    { repository: "auth-service", commits: 123, pullRequests: 18 },
    { repository: "monitoring-tools", commits: 76, pullRequests: 9 },
  ],
  securityAlerts: [
    {
      repository: "backend-api",
      type: "Dependency",
      package: "log4j",
      severity: "critical",
      status: "open",
    },
    {
      repository: "frontend-app",
      type: "Secret",
      package: "API Key",
      severity: "high",
      status: "resolved",
    },
    {
      repository: "data-processor",
      type: "Code Scanning",
      package: "SQL Injection",
      severity: "high",
      status: "in_progress",
    },
    {
      repository: "auth-service",
      type: "Dependency",
      package: "spring-core",
      severity: "medium",
      status: "open",
    },
    {
      repository: "monitoring-tools",
      type: "Secret",
      package: "AWS Credentials",
      severity: "critical",
      status: "resolved",
    },
    {
      repository: "backend-api",
      type: "Code Scanning",
      package: "XSS Vulnerability",
      severity: "medium",
      status: "in_progress",
    },
    {
      repository: "frontend-app",
      type: "Dependency",
      package: "react-scripts",
      severity: "low",
      status: "open",
    },
    {
      repository: "data-processor",
      type: "Secret",
      package: "Database Password",
      severity: "high",
      status: "resolved",
    },
  ],
}

// GitHub CSPM Postures
export const githubCspmPostures = [
  {
    id: 1,
    name: "Repositories Public by Default",
    description: "Enforce private repo defaults",
    status: "warning", // compliant, warning, critical
    lastChecked: "1 hour ago",
    affectedResources: 3,
    category: "Repository",
    remediation: "Change organization settings to make new repositories private by default",
  },
  {
    id: 2,
    name: "No Branch Protection on Default Branch",
    description: "Block force pushes, enforce reviews",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 15,
    category: "Repository",
    remediation: "Enable branch protection rules for all default branches",
  },
  {
    id: 3,
    name: "Secrets in Code Commits",
    description: "Scan for leaked credentials/API keys",
    status: "critical",
    lastChecked: "30 minutes ago",
    affectedResources: 7,
    category: "Security",
    remediation: "Enable secret scanning and remove exposed secrets",
  },
  {
    id: 4,
    name: "Inactive Collaborators with Access",
    description: "Remove dormant users",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 12,
    category: "Access",
    remediation: "Review and remove inactive collaborators from repositories",
  },
  {
    id: 5,
    name: "No SAML SSO Enforced for Org",
    description: "Require SSO for all access",
    status: "compliant",
    lastChecked: "4 hours ago",
    affectedResources: 0,
    category: "Access",
    remediation: "Configure and enforce SAML SSO for the organization",
  },
  {
    id: 6,
    name: "Personal Access Tokens Without Expiry",
    description: "Enforce expiry and scopes",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 23,
    category: "Access",
    remediation: "Configure token expiration policies and limit scopes",
  },
  {
    id: 7,
    name: "No Two-Factor Authentication Required for Members",
    description: "Block non-MFA users",
    status: "compliant",
    lastChecked: "5 hours ago",
    affectedResources: 0,
    category: "Access",
    remediation: "Enforce 2FA for all organization members",
  },
  {
    id: 8,
    name: "Actions Workflows with Untrusted Inputs",
    description: "Detect injection vectors",
    status: "warning",
    lastChecked: "1 hour ago",
    affectedResources: 8,
    category: "Actions",
    remediation: "Review and secure GitHub Actions workflows to prevent injection attacks",
  },
  {
    id: 9,
    name: "Unscoped GitHub Apps",
    description: "Check for excessive permissions",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 5,
    category: "Apps",
    remediation: "Review and limit GitHub App permissions to necessary scopes",
  },
  {
    id: 10,
    name: "OAuth Apps with Wide Access",
    description: "Audit third-party apps",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 4,
    category: "Apps",
    remediation: "Review and restrict OAuth app permissions or remove unnecessary apps",
  },
  {
    id: 11,
    name: "Sensitive Data in Issues or PRs",
    description: "Scan for accidental leaks",
    status: "warning",
    lastChecked: "1 hour ago",
    affectedResources: 3,
    category: "Security",
    remediation: "Implement issue templates and PR guidelines to prevent sensitive data exposure",
  },
  {
    id: 12,
    name: "No Signed Commits Enforcement",
    description: "Require verified commit signatures",
    status: "warning",
    lastChecked: "4 hours ago",
    affectedResources: 18,
    category: "Repository",
    remediation: "Configure branch protection to require signed commits",
  },
  {
    id: 13,
    name: "No IP Allow Lists for GitHub Actions Runners",
    description: "Prevent untrusted source execution",
    status: "warning",
    lastChecked: "5 hours ago",
    affectedResources: 1,
    category: "Actions",
    remediation: "Configure IP allow lists for GitHub Actions runners",
  },
  {
    id: 14,
    name: "Default Branch Not Renamed or Protected",
    description: "main/master exposure",
    status: "compliant",
    lastChecked: "6 hours ago",
    affectedResources: 0,
    category: "Repository",
    remediation: "Rename default branches from 'master' to 'main' and apply protection rules",
  },
  {
    id: 15,
    name: "Actions Reusing Unverified Public Workflows",
    description: "Potential supply chain risk",
    status: "critical",
    lastChecked: "2 hours ago",
    affectedResources: 9,
    category: "Actions",
    remediation: "Review and pin workflow references to specific SHA commits",
  },
  {
    id: 16,
    name: "Audit Log Not Monitored or Exported",
    description: "Lack of visibility on changes",
    status: "warning",
    lastChecked: "12 hours ago",
    affectedResources: 1,
    category: "Monitoring",
    remediation: "Configure audit log streaming to external SIEM or monitoring system",
  },
  {
    id: 17,
    name: "Repository Webhooks Sending to Untrusted URLs",
    description: "Exfiltration vector",
    status: "warning",
    lastChecked: "3 hours ago",
    affectedResources: 2,
    category: "Repository",
    remediation: "Review and validate all webhook endpoints",
  },
  {
    id: 18,
    name: "Dependabot Not Enabled",
    description: "No auto-remediation of CVEs",
    status: "critical",
    lastChecked: "4 hours ago",
    affectedResources: 14,
    category: "Security",
    remediation: "Enable Dependabot alerts and security updates for all repositories",
  },
  {
    id: 19,
    name: "Code Scanning Not Enabled",
    description: "Missed vulnerabilities in source",
    status: "critical",
    lastChecked: "3 hours ago",
    affectedResources: 21,
    category: "Security",
    remediation: "Enable GitHub Advanced Security code scanning for all repositories",
  },
  {
    id: 20,
    name: "Actions Not Limited to Specific Repositories",
    description: "Limit org-wide runner access",
    status: "compliant",
    lastChecked: "5 hours ago",
    affectedResources: 0,
    category: "Actions",
    remediation: "Configure GitHub Actions settings to limit runner access to specific repositories",
  },
]

// GitHub CSPM Summary Data
export const githubCspmSummary = {
  totalResources: 156,
  compliantResources: 98,
  warningResources: 35,
  criticalResources: 23,
  complianceScore: 63,
  lastScan: "2025-04-14 09:15 UTC",
  categoryCompliance: [
    { category: "Repository", compliant: 32, warning: 12, critical: 8 },
    { category: "Access", compliant: 25, warning: 8, critical: 5 },
    { category: "Security", compliant: 18, warning: 5, critical: 7 },
    { category: "Actions", compliant: 12, warning: 7, critical: 3 },
    { category: "Apps", compliant: 8, warning: 3, critical: 0 },
    { category: "Monitoring", compliant: 3, warning: 0, critical: 0 },
  ],
  trendData: [
    { date: "2025-04-08", compliant: 85, warning: 42, critical: 29 },
    { date: "2025-04-09", compliant: 88, warning: 40, critical: 28 },
    { date: "2025-04-10", compliant: 90, warning: 39, critical: 27 },
    { date: "2025-04-11", compliant: 92, warning: 38, critical: 26 },
    { date: "2025-04-12", compliant: 94, warning: 37, critical: 25 },
    { date: "2025-04-13", compliant: 96, warning: 36, critical: 24 },
    { date: "2025-04-14", compliant: 98, warning: 35, critical: 23 },
  ],
}
