// Import cloud-specific mock data
import { mockAwsData, awsCspmPostures, awsCspmSummary } from "./mock-data/aws-data"
import { mockGithubData, githubCspmPostures, githubCspmSummary } from "./mock-data/github-data"
import { mockAzureData, azureCspmPostures, azureCspmSummary } from "./mock-data/azure-data"
import { mockGcpData, gcpCspmPostures, gcpCspmSummary } from "./mock-data/gcp-data"
import { mockCloudAwsData } from "./mock-data/cloud-aws-data"
import { mockCloudGithubData } from "./mock-data/cloud-github-data"

// Helper function to create dates relative to now
const daysAgo = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return (
    date.toISOString().split("T")[0] +
    " " +
    String(date.getHours()).padStart(2, "0") +
    ":" +
    String(date.getMinutes()).padStart(2, "0") +
    ":" +
    String(date.getSeconds()).padStart(2, "0")
  )
}

// Enhance the mock logs with additional JSON data fields
export const mockLogs = [
  {
    id: "log1",
    timestamp: "2025-04-24 08:15:22",
    level: "error",
    source: "AWS EC2",
    message: "Failed login attempt detected",
    user: "admin",
    ipAddress: "203.0.113.42",
    // Additional JSON fields
    requestId: "req-a1b2c3d4",
    sessionId: "sess-12345",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    requestUrl: "https://api.example.com/login",
    statusCode: 401,
    responseTime: 245,
    geoLocation: "Moscow, Russia",
    attemptCount: 5,
    accountLocked: true,
    securityAlert: "Possible brute force attack",
    actionTaken: "IP temporarily blocked",
  },
  {
    id: "log2",
    timestamp: "2025-04-24 08:16:05",
    level: "warning",
    source: "Firewall",
    message: "Unusual outbound traffic detected",
    user: "system",
    ipAddress: "10.0.0.15",
    // Additional JSON fields
    destinationIp: "198.51.100.23",
    destinationPort: 8080,
    protocol: "TCP",
    bytesTransferred: 15482,
    duration: 12.5,
    ruleTriggered: "OUT-UNUSUAL-PORT",
    trafficType: "Data Transfer",
    applicationName: "Unknown Application",
    threatLevel: "Medium",
    recommendedAction: "Investigate traffic pattern",
  },
  {
    id: "log3",
    timestamp: "2025-04-24 08:18:30",
    level: "info",
    source: "Auth Service",
    message: "User password changed successfully",
    user: "john.doe",
    ipAddress: "192.168.1.25",
    // Additional JSON fields
    eventType: "PASSWORD_CHANGE",
    accountId: "acc-7890",
    department: "Engineering",
    clientDevice: "MacBook Pro",
    osVersion: "macOS 12.3.1",
    browserInfo: "Chrome 98.0.4758.102",
    twoFactorUsed: true,
    passwordStrength: "Strong",
    previousPasswordAge: "45 days",
    complianceStatus: "Compliant",
  },
  {
    id: "log4",
    timestamp: "2025-04-24 08:20:15",
    level: "debug",
    source: "API Gateway",
    message: "Rate limit applied to client request",
    user: "api_client_3",
    ipAddress: "198.51.100.42",
    // Additional JSON fields
    apiKey: "apk_*****f4d2",
    endpoint: "/v2/data/process",
    rateLimitQuota: 100,
    currentUsage: 101,
    requestsRemaining: 0,
    resetTime: "2025-04-24 09:20:15",
    throttlePolicy: "Soft",
    serviceLevel: "Standard",
    clientType: "External Partner",
    retryAfter: 60,
  },
  {
    id: "log5",
    timestamp: "2025-04-24 08:25:33",
    level: "error",
    source: "Database",
    message: "Connection pool exhausted",
    user: "system",
    ipAddress: "10.0.0.5",
    // Additional JSON fields
    databaseName: "prod-customer-db",
    instanceId: "db-prod-3",
    maxConnections: 100,
    activeConnections: 100,
    waitingRequests: 25,
    errorCode: "DB-CONN-001",
    stackTrace: "java.sql.SQLException: Connection pool exhausted...",
    impactedServices: ["checkout", "user-profile"],
    autoRecoveryAttempted: true,
    incidentId: "INC-DB-2025-042401",
  },
  {
    id: "log6",
    timestamp: "2025-04-24 08:30:42",
    level: "warning",
    source: "S3 Bucket",
    message: "Public access configuration modified",
    user: "admin",
    ipAddress: "10.0.0.18",
    // Additional JSON fields
    bucketName: "company-assets-prod",
    changeType: "ACL_MODIFIED",
    previousAccess: "Private",
    newAccess: "Public Read",
    objectsAffected: 342,
    sensitiveDataExposed: true,
    modifiedBy: "arn:aws:iam::123456789012:user/admin",
    awsRegion: "us-east-1",
    complianceViolation: "PCI-DSS-7.2.1",
    remediationRequired: true,
  },
  {
    id: "log7",
    timestamp: "2025-04-24 08:35:18",
    level: "info",
    source: "Load Balancer",
    message: "New instance added to pool",
    user: "system",
    ipAddress: "10.0.0.30",
    // Additional JSON fields
    loadBalancerId: "lb-prod-web-01",
    instanceId: "i-0abc123def456",
    availabilityZone: "us-east-1a",
    healthCheckStatus: "Passed",
    responseTime: 28,
    trafficWeight: 100,
    instanceType: "c5.xlarge",
    autoScalingGroup: "asg-web-prod",
    currentCapacity: 8,
    desiredCapacity: 8,
  },
  {
    id: "log8",
    timestamp: "2025-04-24 08:40:55",
    level: "debug",
    source: "Cache Service",
    message: "Cache invalidation triggered",
    user: "deployment",
    ipAddress: "10.0.0.50",
    // Additional JSON fields
    cacheType: "Redis",
    clusterName: "prod-session-cache",
    keysAffected: 15783,
    invalidationPattern: "user:*:session",
    triggerSource: "Deployment Pipeline",
    deploymentId: "deploy-2025-04-24-v35",
    memoryUsageBefore: "78%",
    memoryUsageAfter: "45%",
    invalidationDuration: 3.2,
    cacheHitRatio: "0.92",
  },
  {
    id: "log9",
    timestamp: "2025-04-24 08:45:10",
    level: "error",
    source: "Payment Gateway",
    message: "Transaction processing failed",
    user: "customer-5678",
    ipAddress: "203.0.113.100",
    // Additional JSON fields
    transactionId: "txn-9876543210",
    paymentMethod: "Credit Card",
    amount: 299.99,
    currency: "USD",
    errorCode: "PAYMENT-15",
    errorMessage: "Insufficient funds",
    cardType: "Visa",
    cardLastFour: "4321",
    merchantId: "merch-12345",
    gatewayResponse: "Declined by issuing bank",
  },
  {
    id: "log10",
    timestamp: "2025-04-24 08:50:27",
    level: "warning",
    source: "Kubernetes",
    message: "Pod eviction due to resource constraints",
    user: "system",
    ipAddress: "10.0.0.100",
    // Additional JSON fields
    clusterName: "prod-main",
    namespace: "backend-services",
    podName: "api-server-7abc8def9g-5hjkl",
    nodeName: "worker-node-05",
    evictionReason: "Memory pressure",
    memoryUsage: "95%",
    cpuUsage: "80%",
    podRestartCount: 3,
    serviceImpact: "Minimal - Redundant pods available",
    kubernetesVersion: "1.26.5",
  },
]

// Enhanced mock logs with the structure from the API
export const enhancedMockLogs = {
  statusCode: 200,
  body: {
    message: "Successfully got logs!",
    affinity_logs: {
      records: [
        {
          type: "h2",
          timestamp: "2023-07-18T18:58:00Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "181.46.56.83",
          sourceport: "14003",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "-1",
          backendprocessingtime: "-1",
          responseprocessingtime: "-1",
          albstatuscode: "503",
          backendstatucode: "-",
          receivedbytes: "60",
          sentbytes: "635",
          requestverb: "GET",
          requesturl: "https://api.hermes.pollux.finance:443/socket.io/?room=hermes&EIO=4&transport=polling&t=ObgNeSN",
          requestproto: "HTTP/2.0",
          useragent:
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e0e7-709ac58b1f7c00737adb062e",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "4",
          requestcreationtime: "2023-07-18T18:58:00Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "-",
          "target.portlist": "-",
          "target.codelist": "-",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
        {
          type: "h2",
          timestamp: "2023-07-18T19:02:15Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "52.89.214.238",
          sourceport: "39546",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "0.001",
          backendprocessingtime: "0.012",
          responseprocessingtime: "0.000",
          albstatuscode: "200",
          backendstatucode: "200",
          receivedbytes: "1196",
          sentbytes: "4846",
          requestverb: "POST",
          requesturl: "https://api.hermes.pollux.finance:443/v1/graphql",
          requestproto: "HTTP/2.0",
          useragent:
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e1d7-0d5c7f2b0d5c7f2b0d5c7f2b",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "4",
          requestcreationtime: "2023-07-18T19:02:15Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "-",
          "target.portlist": "10.0.1.21:80",
          "target.codelist": "200",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
        {
          type: "h2",
          timestamp: "2023-07-18T19:05:32Z",
          albname: "app/pollu-LoadB-NZOEWEP1XOE3/b3f73e38753fe372",
          sourceipaddress: "13.57.178.142",
          sourceport: "41890",
          destinationipaddress: "",
          destinationport: "",
          requestprocessingtime: "0.000",
          backendprocessingtime: "0.005",
          responseprocessingtime: "0.000",
          albstatuscode: "200",
          backendstatucode: "200",
          receivedbytes: "624",
          sentbytes: "1256",
          requestverb: "GET",
          requesturl: "https://api.hermes.pollux.finance:443/health",
          requestproto: "HTTP/2.0",
          useragent: "Datadog/Synthetics",
          sslcipher: "TLS_AES_128_GCM_SHA256",
          sslprotocol: "TLSv1.3",
          targetgrouparn:
            "arn:aws:elasticloadbalancing:sa-east-1:250512331985:targetgroup/pollux-Gatew-CLW44ZO5VDOX/dea6caa2da549914",
          traceid: "Root=1-64b6e29c-0d5c7f2b0d5c7f2b0d5c7f2b",
          domainname: "api.hermes.pollux.finance",
          chosencertarn: "arn:aws:acm:sa-east-1:250512331985:certificate/3ee55a40-aab7-4bdf-b5f3-9cd55bb7b6c1",
          matchedrulepriority: "4",
          requestcreationtime: "2023-07-18T19:05:32Z",
          actionsexecuted: "waf,forward",
          redirecturl: "-",
          errorreason: "-",
          "target.portlist": "10.0.1.21:80",
          "target.codelist": "200",
          classification: null,
          classificationreason: null,
          customfield: ' "-"',
        },
      ],
      execution_id: "3aefebf2-5e1b-4008-97cc-b84a053953da",
      headers: [
        "type",
        "timestamp",
        "albname",
        "sourceipaddress",
        "sourceport",
        "destinationipaddress",
        "destinationport",
        "requestprocessingtime",
        "backendprocessingtime",
        "responseprocessingtime",
        "albstatuscode",
        "backendstatucode",
        "receivedbytes",
        "sentbytes",
        "requestverb",
        "requesturl",
        "requestproto",
        "useragent",
        "sslcipher",
        "sslprotocol",
        "targetgrouparn",
        "traceid",
        "domainname",
        "chosencertarn",
        "matchedrulepriority",
        "requestcreationtime",
        "actionsexecuted",
        "redirecturl",
        "errorreason",
        "target.portlist",
        "target.codelist",
        "classification",
        "classificationreason",
        "customfield",
      ],
      records_per_page: 3,
      total_rows: 3,
    },
  },
}

// Mock data for alerts with a mix of current and historical data
export const mockAlerts = [
  {
    id: "alert-001",
    timestamp: daysAgo(0),
    severity: "critical",
    title: "Potential Data Exfiltration Detected",
    description:
      "Unusual outbound data transfer of 2.3GB detected from database server to external IP 203.0.113.42. This behavior matches known data exfiltration patterns.",
    source: "Network Monitor",
    status: "open",
  },
  {
    id: "alert-002",
    timestamp: daysAgo(0),
    severity: "high",
    title: "Brute Force Authentication Attempt",
    description:
      "Multiple failed login attempts (25+) detected for admin account from IP 198.51.100.73 within a 5-minute window.",
    source: "Auth Service",
    status: "investigating",
  },
  {
    id: "alert-003",
    timestamp: daysAgo(1),
    severity: "medium",
    title: "Unusual API Access Pattern",
    description:
      "User 'api-client' accessed sensitive endpoints in an unusual sequence, potentially indicating API enumeration or reconnaissance.",
    source: "API Gateway",
    status: "investigating",
  },
  {
    id: "alert-004",
    timestamp: daysAgo(1),
    severity: "low",
    title: "New Admin User Created",
    description:
      "New administrator account 'backup-admin' was created by user 'jsmith'. This is a routine but security-relevant action.",
    source: "IAM",
    status: "resolved",
  },
  {
    id: "alert-005",
    timestamp: daysAgo(2),
    severity: "critical",
    title: "Ransomware Behavior Detected",
    description:
      "Endpoint protection detected file encryption patterns consistent with ransomware on workstation WS-DEV-042. Automated isolation has been triggered.",
    source: "Endpoint Protection",
    status: "investigating",
  },
  {
    id: "alert-006",
    timestamp: daysAgo(3),
    severity: "high",
    title: "Suspicious Process Execution",
    description:
      "PowerShell executed with encoded command parameters on server SRV-PROD-015, potentially indicating obfuscated malicious activity.",
    source: "EDR",
    status: "open",
  },
  {
    id: "alert-007",
    timestamp: daysAgo(4),
    severity: "medium",
    title: "Firewall Rule Modification",
    description:
      "Production firewall rules were modified to allow additional inbound traffic on port 22 (SSH) from external networks.",
    source: "Firewall",
    status: "resolved",
  },
  {
    id: "alert-008",
    timestamp: daysAgo(5),
    severity: "low",
    title: "SSL Certificate Expiring Soon",
    description:
      "SSL certificate for api.company.com will expire in 15 days. Renewal is required to prevent service disruption.",
    source: "Certificate Monitor",
    status: "open",
  },
  {
    id: "alert-009",
    timestamp: daysAgo(6),
    severity: "high",
    title: "Potential SQL Injection Attempt",
    description:
      "Web application firewall detected and blocked multiple SQL injection attempts against the customer database API.",
    source: "WAF",
    status: "false_positive",
  },
  {
    id: "alert-010",
    timestamp: daysAgo(7),
    severity: "critical",
    title: "Unauthorized Infrastructure Change",
    description:
      "Terraform detected unauthorized changes to production infrastructure that did not go through the CI/CD pipeline.",
    source: "IaC Scanner",
    status: "investigating",
  },
]

// Mock data for analytics with dates
export const mockAnalyticsData = {
  totalEvents: 1245789,
  securityIncidents: 342,
  monitoredResources: 1876,
  eventsOverTime: [
    { date: daysAgo(6).split(" ")[0], events: 145678 },
    { date: daysAgo(5).split(" ")[0], events: 156432 },
    { date: daysAgo(4).split(" ")[0], events: 149876 },
    { date: daysAgo(3).split(" ")[0], events: 162345 },
    { date: daysAgo(2).split(" ")[0], events: 178965 },
    { date: daysAgo(1).split(" ")[0], events: 189543 },
    { date: daysAgo(0).split(" ")[0], events: 192876 },
  ],
  platformDistribution: [
    { name: "AWS", value: 456789 },
    { name: "Azure", value: 345678 },
    { name: "GCP", value: 234567 },
    { name: "GitHub", value: 123456 },
    { name: "On-Premise", value: 85299 },
  ],
  incidentTypes: [
    { name: "Unauthorized Access", count: 87 },
    { name: "Malware", count: 65 },
    { name: "Data Exfiltration", count: 43 },
    { name: "Phishing", count: 76 },
    { name: "Misconfiguration", count: 54 },
    { name: "Insider Threat", count: 17 },
  ],
  topEvents: [
    {
      type: "Failed Login Attempts",
      platform: "AWS",
      count: 12456,
      severity: "high",
      trend: "up",
      trendValue: 12,
      date: daysAgo(0).split(" ")[0],
    },
    {
      type: "Suspicious API Calls",
      platform: "Azure",
      count: 8765,
      severity: "medium",
      trend: "up",
      trendValue: 8,
      date: daysAgo(0).split(" ")[0],
    },
    {
      type: "Firewall Rule Changes",
      platform: "GCP",
      count: 5432,
      severity: "high",
      trend: "down",
      trendValue: 3,
      date: daysAgo(1).split(" ")[0],
    },
    {
      type: "Sensitive Data Access",
      platform: "AWS",
      count: 4321,
      severity: "critical",
      trend: "up",
      trendValue: 15,
      date: daysAgo(1).split(" ")[0],
    },
    {
      type: "Malware Detected",
      platform: "On-Premise",
      count: 3456,
      severity: "critical",
      trend: "down",
      trendValue: 5,
      date: daysAgo(2).split(" ")[0],
    },
    {
      type: "Unusual Network Traffic",
      platform: "Azure",
      count: 2345,
      severity: "medium",
      trend: "up",
      trendValue: 7,
      date: daysAgo(3).split(" ")[0],
    },
    {
      type: "Resource Deletion",
      platform: "GCP",
      count: 1234,
      severity: "high",
      trend: "down",
      trendValue: 2,
      date: daysAgo(4).split(" ")[0],
    },
    {
      type: "Privilege Escalation",
      platform: "AWS",
      count: 987,
      severity: "critical",
      trend: "up",
      trendValue: 20,
      date: daysAgo(5).split(" ")[0],
    },
  ],
}

// Mock data for threat map
export const mockThreatData = [
  { id: 1, latitude: 37.7749, longitude: -122.4194, type: "attack", magnitude: 5, timestamp: daysAgo(0) },
  { id: 2, latitude: 40.7128, longitude: -74.006, type: "attack", magnitude: 4, timestamp: daysAgo(0) },
  { id: 3, latitude: 51.5074, longitude: -0.1278, type: "attack", magnitude: 6, timestamp: daysAgo(1) },
  { id: 4, latitude: 48.8566, longitude: 2.3522, type: "suspicious", magnitude: 3, timestamp: daysAgo(1) },
  { id: 5, latitude: 55.7558, longitude: 37.6173, type: "suspicious", magnitude: 4, timestamp: daysAgo(2) },
  { id: 6, latitude: 35.6762, longitude: 139.6503, type: "suspicious", magnitude: 5, timestamp: daysAgo(2) },
  { id: 7, latitude: 22.3193, longitude: 114.1694, type: "suspicious", magnitude: 3, timestamp: daysAgo(3) },
  { id: 8, latitude: -33.8688, longitude: 151.2093, type: "potential", magnitude: 2, timestamp: daysAgo(3) },
  { id: 9, latitude: 1.3521, longitude: 103.8198, type: "potential", magnitude: 3, timestamp: daysAgo(4) },
  { id: 10, latitude: 25.2048, longitude: 55.2708, type: "potential", magnitude: 2, timestamp: daysAgo(4) },
  { id: 11, latitude: -23.5505, longitude: -46.6333, type: "potential", magnitude: 3, timestamp: daysAgo(5) },
  { id: 12, latitude: 19.4326, longitude: -99.1332, type: "potential", magnitude: 2, timestamp: daysAgo(5) },
  { id: 13, latitude: 28.6139, longitude: 77.209, type: "attack", magnitude: 5, timestamp: daysAgo(6) },
  { id: 14, latitude: 39.9042, longitude: 116.4074, type: "attack", magnitude: 6, timestamp: daysAgo(6) },
  { id: 15, latitude: -34.6037, longitude: -58.3816, type: "suspicious", magnitude: 4, timestamp: daysAgo(7) },
  { id: 16, latitude: 59.3293, longitude: 18.0686, type: "potential", magnitude: 2, timestamp: daysAgo(7) },
  { id: 17, latitude: 52.52, longitude: 13.405, type: "suspicious", magnitude: 3, timestamp: daysAgo(8) },
  { id: 18, latitude: 41.9028, longitude: 12.4964, type: "potential", magnitude: 2, timestamp: daysAgo(8) },
  { id: 19, latitude: 31.2304, longitude: 121.4737, type: "attack", magnitude: 4, timestamp: daysAgo(9) },
  { id: 20, latitude: -6.2088, longitude: 106.8456, type: "suspicious", magnitude: 3, timestamp: daysAgo(9) },
]

// Mock data for system status
export const mockSystemStatus = [
  {
    id: 1,
    name: "Firewall Cluster",
    description: "Edge network protection",
    status: "operational",
    uptime: "99.99%",
    icon: "shield",
    lastUpdated: daysAgo(0),
  },
  {
    id: 2,
    name: "Engine",
    description: "Log aggregation and analysis",
    status: "operational",
    uptime: "99.95%",
    icon: "server",
    lastUpdated: daysAgo(0),
  },
  {
    id: 3,
    name: "Threat Intelligence Feed",
    description: "Real-time threat data",
    status: "operational",
    uptime: "100%",
    icon: "clock",
    lastUpdated: daysAgo(1),
  },
  {
    id: 4,
    name: "Vulnerability Scanner",
    description: "Asset discovery and scanning",
    status: "degraded",
    uptime: "98.72%",
    icon: "shield",
    lastUpdated: daysAgo(1),
  },
  {
    id: 5,
    name: "Endpoint Protection",
    description: "Device security monitoring",
    status: "operational",
    uptime: "99.87%",
    icon: "shield",
    lastUpdated: daysAgo(2),
  },
  {
    id: 6,
    name: "Database Security",
    description: "Data access monitoring",
    status: "down",
    uptime: "95.43%",
    icon: "server",
    lastUpdated: daysAgo(3),
  },
  {
    id: 7,
    name: "Cloud Security Posture",
    description: "Cloud configuration monitoring",
    status: "operational",
    uptime: "99.91%",
    icon: "server",
    lastUpdated: daysAgo(4),
  },
]

// Mock data for integrations
export const mockIntegrationsData = {
  installed: [
    {
      name: "AWS Security Hub",
      description: "Centralized security findings from AWS services",
      lastSync: "10 minutes ago",
      dataSources: "15 sources",
    },
    {
      name: "Azure Sentinel",
      description: "Cloud-native solution",
      lastSync: "15 minutes ago",
      dataSources: "12 sources",
    },
    {
      name: "Google Security Command Center",
      description: "Unified security and risk management for GCP",
      lastSync: "5 minutes ago",
      dataSources: "10 sources",
    },
    {
      name: "CrowdStrike Falcon",
      description: "Endpoint detection and response",
      lastSync: "20 minutes ago",
      dataSources: "8 sources",
    },
    {
      name: "Splunk",
      description: "Data analytics and monitoring platform",
      lastSync: "30 minutes ago",
      dataSources: "20 sources",
    },
    {
      name: "GitHub Advanced Security",
      description: "Code scanning and secret detection",
      lastSync: "45 minutes ago",
      dataSources: "5 sources",
    },
  ],
  available: [
    {
      name: "Okta",
      description: "Identity and access management",
      category: "Identity",
      dataSources: "User authentication, MFA, SSO",
    },
    {
      name: "Palo Alto Networks",
      description: "Next-generation firewall and security platform",
      category: "Network Security",
      dataSources: "Firewall logs, Threat prevention",
    },
    {
      name: "Elastic Security",
      description: "endpoint security",
      category: "SIEM",
      dataSources: "Logs, Metrics, APM",
    },
    {
      name: "Tenable.io",
      description: "Vulnerability management platform",
      category: "Vulnerability Management",
      dataSources: "Scan results, Asset inventory",
    },
    {
      name: "Cloudflare",
      description: "Web security and performance",
      category: "Web Security",
      dataSources: "WAF logs, DDoS protection",
    },
    {
      name: "Datadog",
      description: "Monitoring and security platform",
      category: "Monitoring",
      dataSources: "Logs, Metrics, Traces",
    },
  ],
  activity: [
    {
      integration: "AWS Security Hub",
      event: "Data sync completed",
      status: "success",
      time: "10 minutes ago",
    },
    {
      integration: "Azure Sentinel",
      event: "New connector added",
      status: "success",
      time: "1 hour ago",
    },
    {
      integration: "CrowdStrike Falcon",
      event: "API authentication failed",
      status: "error",
      time: "2 hours ago",
    },
    {
      integration: "Splunk",
      event: "Configuration updated",
      status: "success",
      time: "3 hours ago",
    },
    {
      integration: "GitHub Advanced Security",
      event: "Rate limit warning",
      status: "warning",
      time: "4 hours ago",
    },
    {
      integration: "Google Security Command Center",
      event: "New data source added",
      status: "success",
      time: "5 hours ago",
    },
  ],
}

// Mock data for agents
export const mockAgentsData = {
  totalAgents: 156,
  activeAgents: 142,
  agentsWithIssues: 23,
  criticalIssues: 8,
  outdatedAgents: 15,
  eventsCollected: 1245789,
  eventCollection: [
    { date: daysAgo(6).split(" ")[0], events: 145678 },
    { date: daysAgo(5).split(" ")[0], events: 156432 },
    { date: daysAgo(4).split(" ")[0], events: 149876 },
    { date: daysAgo(3).split(" ")[0], events: 162345 },
    { date: daysAgo(2).split(" ")[0], events: 178965 },
    { date: daysAgo(1).split(" ")[0], events: 189543 },
    { date: daysAgo(0).split(" ")[0], events: 192876 },
  ],
  agentStatusDistribution: [
    { status: "healthy", count: 112 },
    { status: "warning", count: 31 },
    { status: "critical", count: 8 },
    { status: "offline", count: 5 },
  ],
  agentHealth: [
    {
      id: "agent-001",
      hostname: "web-server-01",
      version: "3.2.1",
      status: "healthy",
      lastCheckIn: "2 minutes ago",
      issues: null,
    },
    {
      id: "agent-002",
      hostname: "db-server-01",
      version: "3.2.1",
      status: "healthy",
      lastCheckIn: "5 minutes ago",
      issues: null,
    },
    {
      id: "agent-003",
      hostname: "app-server-01",
      version: "3.1.9",
      status: "warning",
      lastCheckIn: "10 minutes ago",
      issues: "Outdated version",
    },
    {
      id: "agent-004",
      hostname: "web-server-02",
      version: "3.2.1",
      status: "healthy",
      lastCheckIn: "3 minutes ago",
      issues: null,
    },
    {
      id: "agent-005",
      hostname: "db-server-02",
      version: "3.2.0",
      status: "warning",
      lastCheckIn: "15 minutes ago",
      issues: "High CPU usage",
    },
    {
      id: "agent-006",
      hostname: "app-server-02",
      version: "3.1.8",
      status: "critical",
      lastCheckIn: "30 minutes ago",
      issues: "Connection lost",
    },
    {
      id: "agent-007",
      hostname: "web-server-03",
      version: "3.2.1",
      status: "healthy",
      lastCheckIn: "7 minutes ago",
      issues: null,
    },
    {
      id: "agent-008",
      hostname: "db-server-03",
      version: "3.2.1",
      status: "healthy",
      lastCheckIn: "8 minutes ago",
      issues: null,
    },
    {
      id: "agent-009",
      hostname: "app-server-03",
      version: "3.1.9",
      status: "warning",
      lastCheckIn: "20 minutes ago",
      issues: "Outdated version",
    },
    {
      id: "agent-010",
      hostname: "web-server-04",
      version: "3.0.5",
      status: "critical",
      lastCheckIn: "45 minutes ago",
      issues: "Multiple vulnerabilities",
    },
    {
      id: "agent-011",
      hostname: "db-server-04",
      version: "3.2.1",
      status: "offline",
      lastCheckIn: "2 hours ago",
      issues: "Unreachable",
    },
    {
      id: "agent-012",
      hostname: "app-server-04",
      version: "3.2.1",
      status: "healthy",
      lastCheckIn: "12 minutes ago",
      issues: null,
    },
  ],
}

// Mock data for users
export const mockUsersData = {
  totalUsers: 87,
  activeUsers: 72,
  adminUsers: 8,
  pendingInvitations: 5,
  lockedAccounts: 3,
  users: [
    {
      name: "John Smith",
      email: "john.smith@company.com",
      role: "admin",
      lastLogin: "10 minutes ago",
      status: "active",
    },
    {
      name: "Sarah Johnson",
      email: "sarah.johnson@company.com",
      role: "analyst",
      lastLogin: "2 hours ago",
      status: "active",
    },
    {
      name: "Michael Brown",
      email: "michael.brown@company.com",
      role: "user",
      lastLogin: "1 day ago",
      status: "active",
    },
    {
      name: "Emily Davis",
      email: "emily.davis@company.com",
      role: "analyst",
      lastLogin: "3 hours ago",
      status: "active",
    },
    {
      name: "David Wilson",
      email: "david.wilson@company.com",
      role: "admin",
      lastLogin: "5 hours ago",
      status: "active",
    },
    {
      name: "Jessica Martinez",
      email: "jessica.martinez@company.com",
      role: "user",
      lastLogin: "2 days ago",
      status: "inactive",
    },
    {
      name: "Robert Taylor",
      email: "robert.taylor@company.com",
      role: "readonly",
      lastLogin: "1 week ago",
      status: "active",
    },
    {
      name: "Jennifer Anderson",
      email: "jennifer.anderson@company.com",
      role: "analyst",
      lastLogin: "4 hours ago",
      status: "active",
    },
    {
      name: "Christopher Thomas",
      email: "christopher.thomas@company.com",
      role: "user",
      lastLogin: "Never",
      status: "pending",
    },
    {
      name: "Lisa Jackson",
      email: "lisa.jackson@company.com",
      role: "admin",
      lastLogin: "1 hour ago",
      status: "active",
    },
    {
      name: "Daniel White",
      email: "daniel.white@company.com",
      role: "user",
      lastLogin: "3 days ago",
      status: "locked",
    },
    {
      name: "Michelle Harris",
      email: "michelle.harris@company.com",
      role: "analyst",
      lastLogin: "6 hours ago",
      status: "active",
    },
    {
      name: "James Clark",
      email: "james.clark@company.com",
      role: "readonly",
      lastLogin: "2 days ago",
      status: "active",
    },
    {
      name: "Patricia Lewis",
      email: "patricia.lewis@company.com",
      role: "user",
      lastLogin: "Never",
      status: "pending",
    },
    {
      name: "Richard Walker",
      email: "richard.walker@company.com",
      role: "admin",
      lastLogin: "12 hours ago",
      status: "active",
    },
    {
      name: "Elizabeth Hall",
      email: "elizabeth.hall@company.com",
      role: "analyst",
      lastLogin: "1 day ago",
      status: "active",
    },
    {
      name: "Thomas Allen",
      email: "thomas.allen@company.com",
      role: "user",
      lastLogin: "5 days ago",
      status: "inactive",
    },
    {
      name: "Nancy Young",
      email: "nancy.young@company.com",
      role: "readonly",
      lastLogin: "3 days ago",
      status: "active",
    },
    {
      name: "Charles King",
      email: "charles.king@company.com",
      role: "user",
      lastLogin: "Never",
      status: "pending",
    },
    {
      name: "Karen Wright",
      email: "karen.wright@company.com",
      role: "admin",
      lastLogin: "8 hours ago",
      status: "active",
    },
  ],
}

// Export cloud-specific data
export {
  mockAwsData,
  awsCspmPostures,
  awsCspmSummary,
  mockGithubData,
  githubCspmPostures,
  githubCspmSummary,
  mockAzureData,
  azureCspmPostures,
  azureCspmSummary,
  mockGcpData,
  gcpCspmPostures,
  gcpCspmSummary,
  mockCloudAwsData,
  mockCloudGithubData,
}
